spring:
  sleuth:
    sampler:
      percentage: 1.0
  application:
    name: student
server:
  port: 8090
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/